server:
  port: 8000

spring:
    application:
        name: expensetracker
    datasource:
        url: jdbc:mysql://localhost:3306/expenseTracker
        username: root
        password: Ayaan@290103
        driver-class-name: com.mysql.cj.jdbc.Driver
    
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

security:
    secret-key: 2iBf9HdpbqaWQSYOVqyKGCO8VhPSrL40
    jwt:
        access-token-expiration: 86400000
        refresh-token-expiration: 864000000
